### ISSUE TITLE
[BUG] CDF for empirical distribution returns dataframe of objects not floats.

### ISSUE THREAD

**Issue by Alex-JG3** [sktime/skpro#56]
**Describe the bug**

The `cdf` function for the `Empirical` distribution returns daframes with cells that are of data type `object`.

**To Reproduce**

This example is taken from the `get_test_params` for the `Empirical` distribution.

```python
>>> from skpro.distributions.empirical import Empirical
>>> import pandas as pd
>>> spl_idx = pd.MultiIndex.from_product(
...     [[0, 1], [0, 1, 2]], names=["sample", "time"]
... )
>>> spl = pd.DataFrame(
...     [[0, 1], [2, 3], [10, 11], [6, 7], [8, 9], [4, 5]],
...     index=spl_idx,
...     columns=["a", "b"],
... )
>>> spl.values.dtype
dtype('int64')
>>> x = pd.DataFrame(
...     [[0, 1], [2, 3], [10, 11]],
...     index=pd.Index([0, 1, 2]),
...     columns=pd.Index(['a', 'b'])
... )
>>> d = Empirical(spl)
>>> d.cdf(x)
     a    b
0  0.5  0.5
1  0.5  0.5
2  1.0  1.0
>>> d.cdf(x).values.dtype
dtype('O')
```

This problem arose when I was trying to write a test for checking if the `ppf` is the inverse of the `cdf`. Here is an example of what this test might look like and the error I get.

``` python
>>> import numpy as np
>>> x
    a   b
0   0   1
1   2   3
2  10  11
>>> d
Empirical(columns=Index(['a', 'b'], dtype='object'),
          index=Index([0, 1, 2], dtype='int64', name='time'),
          spl=              a   b
sample time
0      0      0   1
       1      2   3
       2     10  11
1      0      6   7
       1      8   9
       2      4   5)
>>> cdf = d.cdf(x)
>>> cdf.values.dtype
dtype('O')
>>> x_approx = d.ppf(cdf)
>>> x.values.dtype
dtype('int64')
>>> x_approx.values.dtype
dtype('O')
>>> np.allclose(x_approx, x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 200, in allclose
  File "/home/alex/documents/skpro/.venv/lib/python3.10/site-packages/numpy/core/numeric.py", line 2270, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "<__array_function__ internals>", line 200, in isclose
  File "/home/alex/documents/skpro/.venv/lib/python3.10/site-packages/numpy/core/numeric.py", line 2377, in isclose
    xfin = isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
The error is because numpy cannot convert the object type to an integer safely for comparison.

**Expected behavior**

The dataframe returned from `cdf` should contains floats not objects.

**Environment**

pip freeze.

```
anyio==3.7.1
backoff==2.2.1
certifi==2023.7.22
cfgv==3.4.0
coverage==7.3.0
distlib==0.3.7
exceptiongroup==1.1.3
execnet==2.0.2
filelock==3.12.2
h11==0.14.0
httpcore==0.17.3
httpx==0.24.1
identify==2.5.27
idna==3.4
iniconfig==2.0.0
joblib==1.3.2
nodeenv==1.8.0
numpy==1.24.4
packaging==23.1
pandas==2.0.3
platformdirs==3.10.0
pluggy==1.3.0
pre-commit==3.3.3
pytest==7.4.0
pytest-cov==4.1.0
pytest-randomly==3.15.0
pytest-timeout==2.1.0
pytest-xdist==3.3.1
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
scikit-base==0.5.1
scikit-learn==1.3.0
scipy==1.11.2
six==1.16.0
skpro @ file:///home/alex/documents/skpro
sniffio==1.3.0
threadpoolctl==3.2.0
tomli==2.0.1
tzdata==2023.3
virtualenv==20.24.3
```

OS:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**Additional context**

**Comment by fkiraly** [comment]
PS: you accidentally raised this in skbase, not skpro - that's why I missed your post earlier.

**Comment by fkiraly** [comment]
ok, I see, you opened it again - closing in favour of now-duplicate #55
